name: CI
run-name: Test code after ${{github.event_name}} by @${{github.actor}}
on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependecies
        run: python -m pip install -r requirements/requirements-dev.txt

      - name: Run tests
        run: python -m pytest
